//! Server for the islands + RPC reference application.
//!
//! Serves the SSR page at `/` and the `#[server]` function at
//! `/api/rpc/add_task`. Run it with:
//!
//! ```sh
//! cargo run -p reference_app_islands_rpc --bin islands_rpc_server
//! ```

use anyhow::Result;
use axum::response::Html;
use axum::routing::{get, post};
use axum::Router;
use reference_app_islands_rpc::{add_task_handler, render_page_for};

/// Port the example listens on. Deliberately outside the 3000-3002 range the
/// reference services use, so it can run alongside them.
const DEFAULT_PORT: u16 = 3100;

async fn index() -> Html<String> {
    Html(render_page_for("/"))
}

async fn about() -> Html<String> {
    Html(render_page_for("/about"))
}

fn build_app() -> Router {
    Router::new()
        .route("/", get(index))
        // A second route exists so the client router has somewhere to go. Both
        // render the same document shell, so the router finds an outlet in the
        // response and swaps rather than falling back to a full page load.
        .route("/about", get(about))
        // The handler is generated by `#[server]`; the route path must match the
        // URL the client half calls, which the macro derives from the fn name.
        .route("/api/rpc/add_task", post(add_task_handler))
}

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt::init();

    let port = std::env::var("KRAB_PORT")
        .ok()
        .and_then(|v| v.parse::<u16>().ok())
        .unwrap_or(DEFAULT_PORT);

    let listener = tokio::net::TcpListener::bind(("127.0.0.1", port)).await?;
    tracing::info!(port, "islands_rpc_example_listening");

    axum::serve(listener, build_app()).await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::body::Body;
    use axum::http::{Request, StatusCode};
    use http_body_util::BodyExt as _;
    use tower::util::ServiceExt as _;

    async fn fetch_page(uri: &str) -> (StatusCode, String) {
        let response = build_app()
            .oneshot(Request::builder().uri(uri).body(Body::empty()).unwrap())
            .await
            .unwrap();

        let status = response.status();
        let bytes = response.into_body().collect().await.unwrap().to_bytes();
        (status, String::from_utf8(bytes.to_vec()).unwrap())
    }

    async fn get_index() -> (StatusCode, String) {
        fetch_page("/").await
    }

    async fn post_add_task(body: &str) -> (StatusCode, String) {
        let response = build_app()
            .oneshot(
                Request::builder()
                    .method("POST")
                    .uri("/api/rpc/add_task")
                    .header("content-type", "application/json")
                    .body(Body::from(body.to_string()))
                    .unwrap(),
            )
            .await
            .unwrap();

        let status = response.status();
        let bytes = response.into_body().collect().await.unwrap().to_bytes();
        (status, String::from_utf8(bytes.to_vec()).unwrap())
    }

    /// 7.3 — the SSR response carries the island wrapper attributes the client
    /// runtime queries on. Served over HTTP, not just rendered in isolation.
    #[tokio::test]
    async fn ssr_response_contains_island_hydration_markers() {
        let (status, body) = get_index().await;

        assert_eq!(status, StatusCode::OK);
        assert!(body.contains(r#"data-island="TaskCounter""#));
        assert!(body.contains(r#"data-island="TaskFilter""#));
        assert!(body.contains(r#"data-krab-boundary-state="ssr""#));
        assert!(body.contains("data-krab-boundary-id="));
    }

    /// The client router needs an outlet in the document it is *currently* on
    /// and in the document it fetches. Both routes must therefore carry the
    /// marker, or a link click degrades to a full page load.
    #[tokio::test]
    async fn every_page_route_serves_a_router_outlet() {
        for route in ["/", "/about"] {
            let (status, body) = fetch_page(route).await;

            assert_eq!(status, StatusCode::OK, "{route} did not serve");
            assert!(
                body.contains("data-krab-router-outlet"),
                "{route} has no router outlet, so navigating to it reloads the document"
            );
            assert!(
                body.contains(r#"href="/about""#) && body.contains(r#"href="/""#),
                "{route} must carry the nav the router intercepts clicks from"
            );
        }
    }

    /// The outlet's *contents* differ per route while the shell does not — that
    /// is what makes the swap meaningful rather than a no-op.
    #[tokio::test]
    async fn the_two_routes_differ_only_inside_the_outlet() {
        let (_, home) = fetch_page("/").await;
        let (_, about) = fetch_page("/about").await;

        assert!(home.contains(r#"data-testid="route-home""#));
        assert!(!home.contains(r#"data-testid="route-about""#));
        assert!(about.contains(r#"data-testid="route-about""#));
        assert!(!about.contains(r#"data-testid="route-home""#));

        // The shell is identical, so nothing outside the outlet needs replacing.
        assert!(about.contains(r#"data-app="islands-rpc""#));
        assert!(about.contains("krab_boot"));
    }

    /// What the router swaps is the outlet's contents, so anything that must
    /// survive a navigation has to be outside it. Re-running the boot script or
    /// rebuilding the nav on every swap would defeat the point of the router.
    ///
    /// A positional check, not a parse: the outlet's own extent is
    /// `krab_client`'s to determine, and that crate does not build for the host.
    #[tokio::test]
    async fn the_nav_and_the_boot_script_sit_outside_the_outlet() {
        let (_, about) = fetch_page("/about").await;

        let outlet_open = about
            .find("data-krab-router-outlet")
            .expect("no outlet in the served document");
        let outlet_close = about.rfind("</main>").expect("outlet is never closed");

        let nav = about
            .find("site-nav")
            .expect("no nav in the served document");
        let boot = about.find("krab_boot").expect("no boot script");
        let content = about
            .find(r#"data-testid="route-about""#)
            .expect("no route content");

        assert!(nav < outlet_open, "the nav must precede the outlet");
        assert!(
            boot > outlet_close,
            "the boot script must follow the outlet"
        );
        assert!(
            content > outlet_open && content < outlet_close,
            "the route content must be inside the outlet"
        );
    }

    /// 7.3 — a valid request returns the expected payload.
    #[tokio::test]
    async fn server_fn_returns_the_expected_payload_for_a_valid_request() {
        let (status, body) = post_add_task(r#"{"title":"write the example"}"#).await;

        assert_eq!(status, StatusCode::OK);

        let payload: serde_json::Value = serde_json::from_str(&body).unwrap();
        assert_eq!(payload["title"], "write the example");
        assert_eq!(payload["total"], 1);
    }

    /// 7.3 — a malformed request is rejected, not silently accepted.
    #[tokio::test]
    async fn server_fn_rejects_a_malformed_request() {
        // Wrong field name: the args struct cannot deserialize.
        let (status, _) = post_add_task(r#"{"nope":"write the example"}"#).await;
        assert_ne!(status, StatusCode::OK, "malformed args must not succeed");

        // Well-formed args, invalid value.
        let (status, _) = post_add_task(r#"{"title":"   "}"#).await;
        assert_ne!(status, StatusCode::OK, "empty title must not succeed");
    }
}
