//! Server for the islands + RPC reference application.
//!
//! Serves the SSR page at `/` and the `#[server]` function at
//! `/api/rpc/add_task`. Run it with:
//!
//! ```sh
//! cargo run -p reference_app_islands_rpc --bin islands_rpc_server
//! ```

use anyhow::Result;
use axum::response::Html;
use axum::routing::{get, post};
use axum::Router;
use reference_app_islands_rpc::{add_task_handler, render_page};

/// Port the example listens on. Deliberately outside the 3000-3002 range the
/// reference services use, so it can run alongside them.
const DEFAULT_PORT: u16 = 3100;

async fn index() -> Html<String> {
    Html(render_page())
}

fn build_app() -> Router {
    Router::new()
        .route("/", get(index))
        // The handler is generated by `#[server]`; the route path must match the
        // URL the client half calls, which the macro derives from the fn name.
        .route("/api/rpc/add_task", post(add_task_handler))
}

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt::init();

    let port = std::env::var("KRAB_PORT")
        .ok()
        .and_then(|v| v.parse::<u16>().ok())
        .unwrap_or(DEFAULT_PORT);

    let listener = tokio::net::TcpListener::bind(("127.0.0.1", port)).await?;
    tracing::info!(port, "islands_rpc_example_listening");

    axum::serve(listener, build_app()).await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::body::Body;
    use axum::http::{Request, StatusCode};
    use http_body_util::BodyExt as _;
    use tower::util::ServiceExt as _;

    async fn get_index() -> (StatusCode, String) {
        let response = build_app()
            .oneshot(Request::builder().uri("/").body(Body::empty()).unwrap())
            .await
            .unwrap();

        let status = response.status();
        let bytes = response.into_body().collect().await.unwrap().to_bytes();
        (status, String::from_utf8(bytes.to_vec()).unwrap())
    }

    async fn post_add_task(body: &str) -> (StatusCode, String) {
        let response = build_app()
            .oneshot(
                Request::builder()
                    .method("POST")
                    .uri("/api/rpc/add_task")
                    .header("content-type", "application/json")
                    .body(Body::from(body.to_string()))
                    .unwrap(),
            )
            .await
            .unwrap();

        let status = response.status();
        let bytes = response.into_body().collect().await.unwrap().to_bytes();
        (status, String::from_utf8(bytes.to_vec()).unwrap())
    }

    /// 7.3 — the SSR response carries the island wrapper attributes the client
    /// runtime queries on. Served over HTTP, not just rendered in isolation.
    #[tokio::test]
    async fn ssr_response_contains_island_hydration_markers() {
        let (status, body) = get_index().await;

        assert_eq!(status, StatusCode::OK);
        assert!(body.contains(r#"data-island="TaskCounter""#));
        assert!(body.contains(r#"data-island="TaskFilter""#));
        assert!(body.contains(r#"data-krab-boundary-state="ssr""#));
        assert!(body.contains("data-krab-boundary-id="));
    }

    /// 7.3 — a valid request returns the expected payload.
    #[tokio::test]
    async fn server_fn_returns_the_expected_payload_for_a_valid_request() {
        let (status, body) = post_add_task(r#"{"title":"write the example"}"#).await;

        assert_eq!(status, StatusCode::OK);

        let payload: serde_json::Value = serde_json::from_str(&body).unwrap();
        assert_eq!(payload["title"], "write the example");
        assert_eq!(payload["total"], 1);
    }

    /// 7.3 — a malformed request is rejected, not silently accepted.
    #[tokio::test]
    async fn server_fn_rejects_a_malformed_request() {
        // Wrong field name: the args struct cannot deserialize.
        let (status, _) = post_add_task(r#"{"nope":"write the example"}"#).await;
        assert_ne!(status, StatusCode::OK, "malformed args must not succeed");

        // Well-formed args, invalid value.
        let (status, _) = post_add_task(r#"{"title":"   "}"#).await;
        assert_ne!(status, StatusCode::OK, "empty title must not succeed");
    }
}
