[package]
name = "krab_server"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
hyper = { version = "1.0", features = ["full"] }
tokio = { workspace = true, features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
bytes = "1.0"
mime_guess = "2.0"
krab_core = { path = "../krab_core" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tower = { workspace = true, features = ["full"] }
tower-http = { workspace = true, features = ["trace", "cors", "fs"] }
tracing.workspace = true
