[package]
name = "krab_macros"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"

[dev-dependencies]
krab_core = { path = "../krab_core", features = ["rest"] }
trybuild = { version = "1.0", features = ["diff"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
